package org.test;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.HashMap;
import java.util.Map;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.NotFoundException;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;


public class MyQR {
    public static void generateQRCode(String data, String path, String charset, Map hashMap, int height, int width)
    throws WriterException, IOException {
        
        BitMatrix matrix = new MultiFormatWriter()
                .encode(new String(data.getBytes(charset), charset), BarcodeFormat.QR_CODE, width, height);
        
        MatrixToImageWriter.writeToFile(matrix, path.substring(path.lastIndexOf('.') + 1), new File(path));
    }
    
    public static void main(String[] args) throws WriterException, IOException, NotFoundException {
        
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        System.out.println("Enter the data to generate QR code");
        String data = br.readLine();
        String path = "QR.png";
        
        Map<EncodeHintType, ErrorCorrectionLevel> hashMap = new HashMap<>();
        
        hashMap.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.L);
        
        generateQRCode(data, path, "UTF-8", hashMap, 200, 200);
        System.out.println(String.format("QR Code Generated by name %s!!! ", path));
    }
}
